/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uh.kasir;

import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dhenarra
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbSignUp = new javax.swing.JButton();
        jbSignIn = new javax.swing.JButton();
        jpPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jtUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(178, 235, 242));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 0));
        jPanel1.setLayout(null);

        jbSignUp.setBackground(new java.awt.Color(102, 102, 0));
        jbSignUp.setFont(new java.awt.Font("Swis721 Hv BT", 1, 14)); // NOI18N
        jbSignUp.setText("Sign Up");
        jbSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSignUpActionPerformed(evt);
            }
        });
        jPanel1.add(jbSignUp);
        jbSignUp.setBounds(160, 340, 110, 30);

        jbSignIn.setBackground(new java.awt.Color(102, 102, 0));
        jbSignIn.setFont(new java.awt.Font("Swis721 Hv BT", 1, 14)); // NOI18N
        jbSignIn.setText("Sign In");
        jbSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSignInActionPerformed(evt);
            }
        });
        jPanel1.add(jbSignIn);
        jbSignIn.setBounds(160, 380, 110, 30);
        jPanel1.add(jpPass);
        jpPass.setBounds(110, 300, 220, 30);

        jLabel1.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        jLabel1.setText("Password");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 270, 80, 30);
        jPanel1.add(jtUser);
        jtUser.setBounds(110, 220, 220, 30);

        jLabel4.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        jLabel4.setText("Username");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, 190, 80, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/20110913133511_Indomart.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(-20, -20, 470, 170);

        jLabel2.setFont(new java.awt.Font("Pristina", 1, 18)); // NOI18N
        jLabel2.setText("Selamat Bekerja Admin, Lakukan Hal Yang Terbaik ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 150, 370, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 460, 430);

        setBounds(0, 0, 456, 463);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSignUpActionPerformed
        // TODO add your handling code here:
        String username = jtUser.getText();
        String password = jpPass.getText();
        
        try{
            try (Statement statement = (Statement) FileKoneksi.GetConnection().createStatement()) {
                statement.executeUpdate("insert into tb_akun(username,password) VALUES ('" + username + "','" + password + "');");
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Selamat! Anda berhasil sign up!");
        } catch (Exception t){
            JOptionPane.showMessageDialog(null, "Mohon maaf, ulangi lagi prosedur");
        }
        
        jtUser.setText("");
        jpPass.setText("");
    }//GEN-LAST:event_jbSignUpActionPerformed

    private void jbSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSignInActionPerformed
        // TODO add your handling code here:
        Connection connection;
        PreparedStatement ps;
        try{
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_utspbo", "root", "");
            ps = connection.prepareStatement("SELECT username, password FROM tb_akun WHERE username = ? AND password = ?");
            ps.setString(1, jtUser.getText());
            ps.setString(2, jpPass.getText());
            ResultSet result = ps.executeQuery();
            if (result.next()) {
                new MainFrame().show();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Salah!");
                jpPass.setText("");
                jtUser.requestFocus();
            }
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "gagal");
        }
    }//GEN-LAST:event_jbSignInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbSignIn;
    private javax.swing.JButton jbSignUp;
    private javax.swing.JPasswordField jpPass;
    private javax.swing.JTextField jtUser;
    // End of variables declaration//GEN-END:variables
}
