/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uh.kasir;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dhenarra
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setJam();
        setTanggal();
        setKasir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jbClear = new javax.swing.JButton();
        jbTambah = new javax.swing.JButton();
        jbTotal = new javax.swing.JButton();
        jtNama = new javax.swing.JTextField();
        jtHarga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtID = new javax.swing.JTextField();
        jtTransaksi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtBanyak = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jbDelete = new javax.swing.JButton();
        jbPrint = new javax.swing.JButton();
        jlTotal = new javax.swing.JLabel();
        jlDisc = new javax.swing.JLabel();
        jtKembali = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jbHitung = new javax.swing.JButton();
        jtBayar = new javax.swing.JTextField();
        jlTotal1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtBarang = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlKasir = new javax.swing.JLabel();
        jlTanggal = new javax.swing.JLabel();
        jlJam = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 102, 0));
        jPanel2.setLayout(null);

        jbClear.setBackground(new java.awt.Color(204, 204, 0));
        jbClear.setText("Clear");
        jbClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClearActionPerformed(evt);
            }
        });
        jPanel2.add(jbClear);
        jbClear.setBounds(330, 140, 80, 30);

        jbTambah.setBackground(new java.awt.Color(204, 204, 0));
        jbTambah.setText("Tambah");
        jbTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTambahActionPerformed(evt);
            }
        });
        jPanel2.add(jbTambah);
        jbTambah.setBounds(330, 80, 80, 30);

        jbTotal.setBackground(new java.awt.Color(204, 204, 0));
        jbTotal.setText("Total");
        jbTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTotalActionPerformed(evt);
            }
        });
        jPanel2.add(jbTotal);
        jbTotal.setBounds(330, 200, 80, 30);
        jPanel2.add(jtNama);
        jtNama.setBounds(120, 130, 180, 30);
        jPanel2.add(jtHarga);
        jtHarga.setBounds(120, 190, 180, 30);

        jLabel4.setFont(new java.awt.Font("Iskoola Pota", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Harga Barang");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 190, 120, 30);

        jLabel7.setFont(new java.awt.Font("Iskoola Pota", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Nama Barang");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 130, 120, 30);

        jLabel8.setFont(new java.awt.Font("Iskoola Pota", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("ID Barang");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 70, 120, 30);

        jtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtIDActionPerformed(evt);
            }
        });
        jPanel2.add(jtID);
        jtID.setBounds(120, 70, 180, 30);

        jtTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTransaksiActionPerformed(evt);
            }
        });
        jPanel2.add(jtTransaksi);
        jtTransaksi.setBounds(120, 10, 180, 30);

        jLabel9.setFont(new java.awt.Font("Iskoola Pota", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("ID Transaksi");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 10, 120, 30);

        jLabel6.setFont(new java.awt.Font("Iskoola Pota", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Banyak Barang");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 250, 120, 30);
        jPanel2.add(jtBanyak);
        jtBanyak.setBounds(120, 250, 180, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(450, 160, 420, 340);

        jPanel3.setBackground(new java.awt.Color(153, 153, 0));
        jPanel3.setLayout(null);

        jbDelete.setBackground(new java.awt.Color(204, 255, 0));
        jbDelete.setText("Delete");
        jbDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(jbDelete);
        jbDelete.setBounds(320, 40, 110, 30);

        jbPrint.setBackground(new java.awt.Color(204, 255, 0));
        jbPrint.setText("Print");
        jbPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrintActionPerformed(evt);
            }
        });
        jPanel3.add(jbPrint);
        jbPrint.setBounds(320, 120, 110, 30);

        jlTotal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlTotal.setText("0,00");
        jPanel3.add(jlTotal);
        jlTotal.setBounds(210, 0, 220, 40);

        jlDisc.setFont(new java.awt.Font("Iskoola Pota", 1, 14)); // NOI18N
        jlDisc.setForeground(new java.awt.Color(51, 51, 51));
        jlDisc.setText("Disc. 0%");
        jPanel3.add(jlDisc);
        jlDisc.setBounds(220, 50, 60, 30);
        jPanel3.add(jtKembali);
        jtKembali.setBounds(70, 130, 150, 30);

        jLabel11.setFont(new java.awt.Font("Iskoola Pota", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Kembali");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 130, 110, 30);

        jbHitung.setBackground(new java.awt.Color(204, 255, 0));
        jbHitung.setText("Hitung");
        jbHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHitungActionPerformed(evt);
            }
        });
        jPanel3.add(jbHitung);
        jbHitung.setBounds(320, 80, 110, 30);
        jPanel3.add(jtBayar);
        jtBayar.setBounds(70, 50, 150, 30);

        jlTotal1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlTotal1.setText("Total:Rp.");
        jPanel3.add(jlTotal1);
        jlTotal1.setBounds(100, 0, 220, 40);

        jLabel10.setFont(new java.awt.Font("Iskoola Pota", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Bayar ");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 50, 110, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 320, 450, 180);

        jScrollPane1.setBackground(new java.awt.Color(0, 204, 204));
        jScrollPane1.setForeground(new java.awt.Color(0, 153, 153));

        jtBarang.setForeground(new java.awt.Color(255, 255, 255));
        jtBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Barang", "Nama Barang", "Banyak Barang", "Harga Barang", "Jumlah"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtBarang);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 160, 450, 160);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sidomar.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 190, 190);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("DFPOP1-W9", 1, 24)); // NOI18N
        jLabel1.setText("Indomaret Cabang Sawojajar");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 50, 340, 40);

        jLabel3.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N
        jLabel3.setText("Temukan Kebutuhan Anda di Swalayan Kami");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 110, 350, 19);

        jLabel5.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N
        jLabel5.setText("Melayani Anda Dengan Sepenuh Hati");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 90, 290, 19);

        jlKasir.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        jlKasir.setText("Kasir : Iqbal ALbana");
        jPanel1.add(jlKasir);
        jlKasir.setBounds(460, 0, 220, 30);

        jlTanggal.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        jlTanggal.setText("Selasa, 14/03/2017");
        jPanel1.add(jlTanggal);
        jlTanggal.setBounds(490, 20, 170, 30);

        jlJam.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        jlJam.setText("08:05");
        jPanel1.add(jlJam);
        jlJam.setBounds(550, 50, 50, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(190, 0, 680, 160);

        setBounds(0, 0, 884, 537);
    }// </editor-fold>//GEN-END:initComponents

    private void jbTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTambahActionPerformed
        // TODO add your handling code here:
        int transaksi = Integer.parseInt(jtTransaksi.getText());
        int banyak = Integer.parseInt(jtBanyak.getText());
        int harga = Integer.parseInt(jtHarga.getText());
        int jumlah = banyak * harga;
        if ("".equals(jtNama.getText()) || "".equals(jtBanyak.getText()) || "".equals(jtHarga.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            
            String SQL = "INSERT INTO tb_transaksi (id_transaksi, id_barang,nama_barang,banyak_barang,harga_barang,jumlah) "
                    + "VALUES(" + transaksi+ ",'" + jtID.getText() + "','" + jtNama.getText() + "'," + banyak + "," + harga + ","
                    + jumlah + ")";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbTambahActionPerformed

    private void jtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtIDActionPerformed

    private void jtTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTransaksiActionPerformed

    private void jbClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClearActionPerformed
        // TODO add your handling code here:
        jtTransaksi.setText("");
        jtID.setText("");
        jtNama.setText("");
        jtBanyak.setText("");
        jtHarga.setText("");
    }//GEN-LAST:event_jbClearActionPerformed

    private void jbTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTotalActionPerformed
        // TODO add your handling code here:
        totalHarga();
    }//GEN-LAST:event_jbTotalActionPerformed

    private void jbHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHitungActionPerformed
        // TODO add your handling code here:
        int bayar = Integer.parseInt(jtBayar.getText());
        int total = Integer.parseInt(jlTotal.getText());
        int kembali = bayar-total;
        jtKembali.setText(kembali+"");
    }//GEN-LAST:event_jbHitungActionPerformed

    private void jbDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteActionPerformed
        // TODO add your handling code here:
        int baris = jtBarang.getSelectedRow();
        if (baris != -1) {
            String id = jtBarang.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_transaksi WHERE id_barang='"+id+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbDeleteActionPerformed

    private void jtBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtBarangMouseClicked
        // TODO add your handling code here:
        int baris = jtBarang.getSelectedRow();
        if (baris != -1) {
            jtID.setText(jtBarang.getValueAt(baris, 0).toString());
            jtNama.setText(jtBarang.getValueAt(baris, 1).toString());
            jtBanyak.setText(jtBarang.getValueAt(baris, 2).toString());
            jtHarga.setText(jtBarang.getValueAt(baris, 3).toString());}
    }//GEN-LAST:event_jtBarangMouseClicked

    private void jbPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Transaksi Pembelian");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}     ");
        try {
            jtBarang.print(JTable.PrintMode.FIT_WIDTH,header,footer,true,null,true,null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_jbPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbClear;
    private javax.swing.JButton jbDelete;
    private javax.swing.JButton jbHitung;
    private javax.swing.JButton jbPrint;
    private javax.swing.JButton jbTambah;
    private javax.swing.JButton jbTotal;
    private javax.swing.JLabel jlDisc;
    private javax.swing.JLabel jlJam;
    private javax.swing.JLabel jlKasir;
    private javax.swing.JLabel jlTanggal;
    private javax.swing.JLabel jlTotal;
    private javax.swing.JLabel jlTotal1;
    private javax.swing.JTextField jtBanyak;
    private javax.swing.JTable jtBarang;
    private javax.swing.JTextField jtBayar;
    private javax.swing.JTextField jtHarga;
    private javax.swing.JTextField jtID;
    private javax.swing.JTextField jtKembali;
    private javax.swing.JTextField jtNama;
    private javax.swing.JTextField jtTransaksi;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"ID Barang","Nama Barang","Banyak Barang","Harga Barang","Jumlah"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        int transaksi = Integer.parseInt(jtTransaksi.getText());
        String SQL = "SELECT id_barang,nama_barang,banyak_barang,harga_barang,jumlah FROM tb_transaksi where id_transaksi='"+transaksi+"'";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
                String id= rs.getString(1);
                String nama= rs.getString(2);
                String banyak= rs.getString(3);
                String harga= rs.getString(4);
                String jumlah= rs.getString(5);
                String data[] = {id, nama,banyak,harga, jumlah};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtBarang.setModel(dtm);
    }

    private void setJam() {
    {
        ActionListener taskPerformer = new ActionListener()
        {
            public void actionPerformed(ActionEvent evt)
            {
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                if(nilai_jam<=9)
                {
                    nol_jam="0";
                }
                if(nilai_menit<=9)
                {
                    nol_menit="0";
                }
                if(nilai_detik<=9)
                {
                    nol_detik="0";
                }
                String jam = nol_jam+Integer.toString(nilai_jam);
                String menit = nol_menit+Integer.toString(nilai_menit);
                String detik = nol_detik+Integer.toString(nilai_detik);
                jlJam.setText(jam+":"+menit+":"+detik);
            }
        };
        new Timer(100, taskPerformer).start();
    } //To change body of generated methods, choose Tools | Templates.
    }

    private void setTanggal() {
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd-MM-yyyy");
        jlTanggal.setText(kal.format(skrg));
    }

    private void setKasir() {
         String SQL = "SELECT * FROM tb_akun";
        ResultSet result = KoneksiDB.executeQuery(SQL);
        try {
            while(result.next()){
                String namaKasir = result.getString(1);
                jlKasir.setText(namaKasir);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void totalHarga() {
        int banyak = jtBarang.getRowCount();
        int hasil = 0;
        for (int i = 0; i < banyak; i++) {
            hasil += Integer.parseInt(jtBarang.getValueAt(i, 4).toString());
        }
        if (hasil > 100000) {
            int disc = (int) (hasil * 0.15);
            hasil -= disc;
            jlDisc.setText("Disc. 30%");
        }
        jlTotal.setText(String.valueOf(hasil));
    }
}
